### ISSUE TITLE
Support for Bootstrap 4.0 ?

### ISSUE THREAD

**Issue by AmirGilboa** [third774/ng-bootstrap-form-validation#30] opened 2018-02-04 18:51 UTC
I have added this to my project, that is using bootstrap 4.0 (not beta). It works, expect for the coloring. obviously a css mismatch. a quick look revealed that the validation classes have changed between bs4alpha/beta and the final 4.0 .  this project is using classes like 'has-error', while the new classes are 'is-valid', 'is-invalid', etc. as can be seen here:
https://getbootstrap.com/docs/4.0/components/forms/#validation

would be really great if you could update, as this is a true life saver. thanks!

**Comment by jhotujec** [comment] 2018-02-05 11:27
+1 for this. It would be really helpful

**Comment by kingcody** [comment] 2018-02-06 20:41
Duplicate of #28

**Closed by kingcody** 2018-02-06 20:41 UTC
