### ISSUE TITLE
Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by paulrobello** [third774/ng-bootstrap-form-validation#5] opened 2017-09-12 17:07 UTC
Angular 4.4.0-RC.0
When adding NgBootstrapFormValidationModule.forRoot() to my  app.moudle.ts it compiles ok but i get the following error in browser:
Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by third774** [comment] 2017-10-01 21:11
Can you provide some more information on how to reproduce this? What does your `app.module.ts` file look like?

**Comment by JustinLutsky** [comment] 2017-11-16 06:28
Angular 5.0.1, Angular-CLI 1.5.0, Typescript 2.6.1

Having the same issue.

Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

This is my app.module.ts

***

import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { NgBootstrapFormValidationModule } from 'ng-bootstrap-form-validation';

import { AppComponent } from './app.component';
import { CoreModule } from './core/core.module';
import { PublicModule } from './public/public.module';
import { PrivateModule } from './private/private.module';
import { AppRoutingModule } from './app-routing.module';
import { LayoutModule } from './core/layout/layout.module';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    CoreModule,
    LayoutModule,
    NgBootstrapFormValidationModule.forRoot(),
    PublicModule,
    PrivateModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}

**Comment by kingcody** [comment] 2017-12-27 22:49
@JustinLutsky @third774 @oaHgnaW, I also had this problem when using this library with an Angular 5 project. For discussion purposes, I have posted a PR #15 with updated dependencies. Is anyone here aware if there is a backwards compatible upgrade path with Angular 5.x?

**Comment by third774** [comment] 2018-01-05 04:54
@JustinLutsky - v2.0.0 has just been released which fixes Angular 5 support.

Closing this issue as unable to reproduce the v4.x issue.

**Closed by third774** 2018-01-05 04:54 UTC
