### ISSUE TITLE
it does not support angular5.0

### ISSUE THREAD

**Issue by oaHgnaW** [third774/ng-bootstrap-form-validation#13] opened 2017-12-15 03:15 UTC

**Comment by kingcody** [comment] 2017-12-22 23:48
While I'm not sure what issue @oaHgnaW might be having, I don't have an issue with JIT compiling but I do get a runtime error:
```
Uncaught (in promise): Error: Unexpected value '[object Object]' imported by the
module 'WarrantyModule'. Please add a @NgModule annotation.\nsyntaxError
....
```

Commenting out `NgBootstrapFormValidationModule.forRoot()` from my imports does squelch this error. I'm wondering if this issue might be solved by upgrading to one of the newer RC versions of `ng-packagr`. There seem to be some decent changes being made to accommodate the updates with angular, typescript, and friends.

**Comment by oaHgnaW** [comment] 2017-12-26 03:46
i got the same error with you, did you solved this question by upgrading to one of the newer RC versions of ng-packagr? if you do,please kindly tell me ,thks

**Comment by kingcody** [comment] 2017-12-27 20:42
Honestly I believe this to be a duplicate of #5. I think we should "redirect" our conversation there.

**Comment by third774** [comment] 2018-01-05 04:47
Just published a release that should fix Angular 5 support.

**Closed by third774** 2018-01-05 04:47 UTC

**Comment by vvolodin** [comment] 2018-01-11 15:44
Where is the release published? I'm having this with the latest npm package.

**Comment by third774** [comment] 2018-01-11 16:11
@vvolodin - it is published to npm. Which version do you have installed?

https://www.npmjs.com/package/ng-bootstrap-form-validation

**Comment by third774** [comment] 2018-01-11 17:04
@vvolodin - could you share the dependencies section of your `package.json` file?

**Comment by vvolodin** [comment] 2018-01-11 18:41
figured it out, the 'latest' on npm is 1.0.11
`1.0.11 is the latest of 22 releases`
I've installed 2.0 manually and it's working fine.

**Comment by third774** [comment] 2018-01-11 19:42
Ah, crap. I'll fix that tonight. Thanks for finding that!

**Comment by third774** [comment] 2018-01-11 19:45
Created a new issue to track this problem here: https://github.com/third774/ng-bootstrap-form-validation/issues/21
