### ISSUE TITLE
Support for bootstrap 4

### ISSUE THREAD

**Issue by joelmuskwe** [third774/ng-bootstrap-form-validation#27] opened 2018-01-30 06:40 UTC
According to bootstrap 4 Replaced the .has-error, .has-warning, and .has-success classes with HTML5 form validation via CSS’s :invalid and :valid pseudo-classes.

hence no styling is showing for errors.

**Comment by third774** [comment] 2018-01-30 13:51
Duplicate of https://github.com/third774/ng-bootstrap-form-validation/issues/10

**Comment by kingcody** [comment] 2018-01-30 19:33
@joelmuskwe we're most likely going to have to implement this with "[server side](https://getbootstrap.com/docs/4.0/components/forms/#server-side)" validation classes.

**Comment by kingcody** [comment] 2018-01-30 23:21
@joelmuskwe I'd like to move this over to a general Bootstrap 3/4 support issue #28.

**Closed** 2018-02-04 07:13 UTC
